"use client";
/* ═══════════════════════════════════════
   usePdf
   Converts: showPrescriptionPDF (L3553),
   showAnalyticsPDF (L3777), openPDFPreview,
   closePDFPreview, openPDFInNewWindow, triggerPrint
═══════════════════════════════════════ */
import { useState, useCallback, useRef } from 'react';

interface PdfState {
  open: boolean;
  title: string;
  html: string;
}

export function usePdf() {
  const [pdfState, setPdfState] = useState<PdfState>({ open: false, title: '', html: '' });
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // ── Open PDF preview (original openPDFPreview) ──
  const openPdf = useCallback((title: string, html: string) => {
    setPdfState({ open: true, title, html });
  }, []);

  // ── Close PDF preview (original closePDFPreview) ──
  const closePdf = useCallback(() => {
    setPdfState({ open: false, title: '', html: '' });
  }, []);

  // ── Open in new window (original openPDFInNewWindow) ──
  const openInNewWindow = useCallback(() => {
    const w = window.open('', '_blank');
    if (w) {
      w.document.write(pdfState.html);
      w.document.close();
    }
  }, [pdfState.html]);

  // ── Print (original triggerPrint) ──
  const triggerPrint = useCallback(() => {
    if (iframeRef.current?.contentWindow) {
      iframeRef.current.contentWindow.print();
    } else {
      const w = window.open('', '_blank');
      if (w) {
        w.document.write(pdfState.html);
        w.document.close();
        setTimeout(() => w.print(), 300);
      }
    }
  }, [pdfState.html]);

  // ── Generate Prescription PDF HTML (original showPrescriptionPDF L3553) ──
  const generateRxPdfHtml = useCallback((data: {
    clinicName: string; doctorName: string; patientName: string;
    date: string; diagnosis: string;
    remedies: { name: string; potency: string; dosage: string; frequency: string; duration: string }[];
    diet: string[]; instructions: string;
  }) => {
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>
  body { font-family: 'Plus Jakarta Sans', Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1c2b3a; }
  .header { text-align: center; border-bottom: 3px solid #2d5a3d; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { color: #2d5a3d; font-size: 22px; margin: 0; }
  .header p { color: #6b7f94; font-size: 12px; margin: 4px 0; }
  .rx-symbol { font-size: 28px; color: #2d5a3d; font-weight: bold; margin: 16px 0 8px; }
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 20px; font-size: 13px; }
  .info-label { color: #6b7f94; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
  .info-value { font-weight: 600; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #2d5a3d; color: white; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; }
  td { padding: 8px 12px; border-bottom: 1px solid #e4e8e0; font-size: 13px; }
  .diet { background: #fdf0f0; border: 1px solid #f0c5c0; border-radius: 8px; padding: 12px; margin: 16px 0; }
  .diet-title { font-weight: 700; color: #8b1a1a; font-size: 12px; margin-bottom: 6px; }
  .instructions { background: #f0f7f2; border: 1px solid #e4f0e8; border-radius: 8px; padding: 12px; margin: 16px 0; }
  .footer { margin-top: 40px; border-top: 1px solid #cdd7e2; padding-top: 16px; display: flex; justify-content: space-between; font-size: 12px; color: #6b7f94; }
  .signature { text-align: right; }
  .signature-line { width: 200px; border-top: 1px solid #1c2b3a; margin-top: 40px; padding-top: 4px; }
</style></head><body>
  <div class="header">
    <h1>🌿 ${data.clinicName}</h1>
    <p>${data.doctorName} · Homeopathic Physician</p>
  </div>
  <div class="rx-symbol">℞</div>
  <div class="info-grid">
    <div><div class="info-label">Patient</div><div class="info-value">${data.patientName}</div></div>
    <div><div class="info-label">Date</div><div class="info-value">${data.date}</div></div>
    <div style="grid-column:1/-1"><div class="info-label">Diagnosis</div><div class="info-value">${data.diagnosis || 'As discussed'}</div></div>
  </div>
  <table>
    <thead><tr><th>Remedy</th><th>Potency</th><th>Dosage</th><th>Frequency</th><th>Duration</th></tr></thead>
    <tbody>${data.remedies.map(r => `<tr><td><strong>${r.name}</strong></td><td>${r.potency}</td><td>${r.dosage}</td><td>${r.frequency}</td><td>${r.duration}</td></tr>`).join('')}</tbody>
  </table>
  ${data.diet.length ? `<div class="diet"><div class="diet-title">⚠ Diet Restrictions</div>${data.diet.join(' · ')}</div>` : ''}
  ${data.instructions ? `<div class="instructions"><strong>Instructions:</strong> ${data.instructions}</div>` : ''}
  <div class="footer">
    <div>Generated by HerbaMed Pro · ${new Date().toLocaleDateString()}</div>
    <div class="signature"><div class="signature-line">${data.doctorName}</div></div>
  </div>
</body></html>`;
  }, []);

  // ── Generate Analytics PDF HTML (original showAnalyticsPDF L3777) ──
  const generateAnalyticsPdfHtml = useCallback((data: {
    period: string; revenue: string; patients: number; retention: string;
  }) => {
    return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
  h1 { color: #2d5a3d; border-bottom: 3px solid #2d5a3d; padding-bottom: 12px; }
  .stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 24px 0; }
  .stat { background: #f0f7f2; padding: 16px; border-radius: 8px; text-align: center; }
  .stat-val { font-size: 28px; font-weight: bold; color: #2d5a3d; }
  .stat-label { font-size: 12px; color: #6b7f94; text-transform: uppercase; margin-top: 4px; }
  .footer { margin-top: 40px; text-align: center; color: #6b7f94; font-size: 12px; }
</style></head><body>
  <h1>📊 HerbaMed Pro — Analytics Report</h1>
  <p>Period: ${data.period} · Generated: ${new Date().toLocaleDateString()}</p>
  <div class="stat-grid">
    <div class="stat"><div class="stat-val">${data.revenue}</div><div class="stat-label">Revenue</div></div>
    <div class="stat"><div class="stat-val">${data.patients}</div><div class="stat-label">Patients</div></div>
    <div class="stat"><div class="stat-val">${data.retention}</div><div class="stat-label">Retention</div></div>
  </div>
  <div class="footer">HerbaMed Pro · Confidential</div>
</body></html>`;
  }, []);

  return {
    pdfState, iframeRef,
    openPdf, closePdf,
    openInNewWindow, triggerPrint,
    generateRxPdfHtml, generateAnalyticsPdfHtml,
  };
}
